templateDir: ./sdk-resources/beta-resources
packageName: beta
packageVersion: 1.0.0
generateInterfaces: false
enumClassPrefix: false
disallowAdditionalPropertiesIfNotPresent: false
useOneOfDiscriminatorLookup: false