templateDir: ./sdk-resources/resources
packageName: cc
packageVersion: 2.0.0
generateInterfaces: false
enumClassPrefix: false
disallowAdditionalPropertiesIfNotPresent: false
useOneOfDiscriminatorLookup: false
