templateDir: ./sdk-resources/resources
packageName: cc
packageVersion: 1.2.0
generateInterfaces: false
enumClassPrefix: false
disallowAdditionalPropertiesIfNotPresent: false
useOneOfDiscriminatorLookup: false
