templateDir: ./sdk-resources/resources
packageName: cc
packageVersion: 1.1.1
generateInterfaces: false
enumClassPrefix: false
disallowAdditionalPropertiesIfNotPresent: false
useOneOfDiscriminatorLookup: false
