templateDir: ./sdk-resources/cc-resources
packageName: cc
packageVersion: 1.0.0
generateInterfaces: false
enumClassPrefix: false
disallowAdditionalPropertiesIfNotPresent: false
useOneOfDiscriminatorLookup: false