templateDir: ./sdk-resources/resources
packageName: cc
packageVersion: 1.0.5
generateInterfaces: false
enumClassPrefix: false
disallowAdditionalPropertiesIfNotPresent: false
useOneOfDiscriminatorLookup: false
