templateDir: ./sdk-resources/resources
packageName: api_cc
packageVersion: 2.0.1
generateInterfaces: false
disallowAdditionalPropertiesIfNotPresent: false
useOneOfDiscriminatorLookup: false
enumClassPrefix: true
gitRepoId: golang-sdk/v2
gitUserId: sailpoint-oss
