templateDir: ./sdk-resources/resources
packageName: v2
packageVersion: 1.0.5
generateInterfaces: false
enumClassPrefix: false
disallowAdditionalPropertiesIfNotPresent: false
useOneOfDiscriminatorLookup: false
