templateDir: ./sdk-resources/resources
packageName: v2
packageVersion: 1.1.7
generateInterfaces: false
enumClassPrefix: false
disallowAdditionalPropertiesIfNotPresent: false
useOneOfDiscriminatorLookup: false
