templateDir: ./sdk-resources/resources
packageName: v2
packageVersion: 1.1.3
generateInterfaces: false
enumClassPrefix: false
disallowAdditionalPropertiesIfNotPresent: false
useOneOfDiscriminatorLookup: false
